#!/usr/bin/env ruby
require_relative './app'

def introduction
  puts 'Welcome to School Library App!'
  puts ''
  puts 'Please choose an option by entering a number:'
  puts '1 - List all books'
  puts '2 - List all people'
  puts '3 - Create a person'
  puts '4 - Create a book'
  puts '5 - Create a rental'
  puts '6 - List all rentals for a given person id'
  puts '7 - Exit'
end

def options_one(option)
  case option
  when 1
    list_books
  when 2
    list_people
  when 3
    App.create_person
  end
end

def options_two(option)
  case option

  when 4
    create_book
  when 5
    create_rental
  when 6
    list_rentals
  when 7
    puts 'Thank you for using this app!'
  end
end

def checker(option)
  if option >= 1 && option <= 7
    options_one(option)
    if option > 3 && option < 8
      options_two(option)
    else
      puts 'That is not a valid option'
    end
  else
    puts 'That is not a valid option'
  end
end

def main
  introduction
  option = gets.chomp.to_i
  checker(option)
end

main
